# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a6191c291a1ab759c89b1dc2cf0119f2cb358fc09aedb93c3f79c276ebea4c2e61539136b7d7b76d394f6cb737874e465515c59c16e7a3bfed4648dca57f55b

test:
  secret_key_base: 140a8682c8bc2d056322aba92689128a68a61982e85b7ce7fc2f438c07c93c7193180d973718376dcbf25304a19b2e0f4e9199ba094b9db00483eef8214e3623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
